// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj7kQ0NFFa5dAaDVXV-qjZ6uSnliT35Pg',
    appId: '1:1024841860416:web:b09ea630c459ad685be6a5',
    messagingSenderId: '1024841860416',
    projectId: 'uoitc-6746d',
    authDomain: 'uoitc-6746d.firebaseapp.com',
    databaseURL: 'https://uoitc-6746d.firebaseio.com',
    storageBucket: 'uoitc-6746d.appspot.com',
    measurementId: 'G-KFL58XKF1P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYUF8owgoa8Y1JXGOIaMlhbtLBQV2kT1I',
    appId: '1:1024841860416:android:2389bcb6e3f70d3c5be6a5',
    messagingSenderId: '1024841860416',
    projectId: 'uoitc-6746d',
    databaseURL: 'https://uoitc-6746d.firebaseio.com',
    storageBucket: 'uoitc-6746d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKGT0iek5OxBENceyBK3-AWk5euBheoVA',
    appId: '1:1024841860416:ios:6089e6f36bba45235be6a5',
    messagingSenderId: '1024841860416',
    projectId: 'uoitc-6746d',
    databaseURL: 'https://uoitc-6746d.firebaseio.com',
    storageBucket: 'uoitc-6746d.appspot.com',
    iosClientId: '1024841860416-sfi2neco1lfq2ailhnsb7po18g3htg98.apps.googleusercontent.com',
    iosBundleId: 'iq.edu.uoitc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKGT0iek5OxBENceyBK3-AWk5euBheoVA',
    appId: '1:1024841860416:ios:258b4b199bc2013a5be6a5',
    messagingSenderId: '1024841860416',
    projectId: 'uoitc-6746d',
    databaseURL: 'https://uoitc-6746d.firebaseio.com',
    storageBucket: 'uoitc-6746d.appspot.com',
    iosBundleId: 'iq.edu.uoitc.RunnerTests',
  );
}
